name: tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "2.7"
          # Having issues installing Python v3.0-v3.4 on macos and ubuntu - disabling them for now
          #- "3.0"
          #- "3.1"
          #- "3.2"
          #- "3.3"
          #- "3.4"
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python v${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package and test dependencies
      run: |
        pip install -e .[tests]

    - name: Run tests
      run: |
        py.test --cov=bracelogger
