name: tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          # coverage (used by pytest-cov) fails to install on 3.4 (setup.py contains an f-string)
          #- "3.4"
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
          - "pypy2.7"
          - "pypy3.6"
          - "pypy3.7"
          - "pypy3.8"
          - "pypy3.9"
        exclude:
          # https://foss.heptapod.net/pypy/pypy/-/issues/3314
          - os: macos-latest
            python-version: "pypy3.6"
          # PyPy v3.6 not available on Windows
          - os: windows-latest
            python-version: "pypy3.6"
          # 3.5 and 3.6 no longer available on ubuntu-latest
          - os: ubuntu-latest
            python-version: "3.5"
          - os: ubuntu-latest
            python-version: "3.6"
        # Python v3.0-v3.3 can only be installed on Windows
          - python-version: "3.0"
          - python-version: "3.1"
          - python-version: "3.2"
          - python-version: "3.3"
        include:
          - os: windows-latest
            python-version: "3.0"
          - os: windows-latest
            python-version: "3.1"
          - os: windows-latest
            python-version: "3.2"
          - os: windows-latest
            python-version: "3.3"
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python v${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package and test dependencies
      run: |
        pip install -e .[tests]

    - name: Run tests
      run: |
        py.test --cov=bracelogger
